name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # ✅ Fix for PyAudio build on Ubuntu
      - name: Install PortAudio dependency (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y portaudio19-dev

      # ✅ Fix for PyAudio build on macOS
      - name: Install PortAudio dependency (macOS only)
        if: runner.os == 'macOS'
        run: brew install portaudio

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
