name: Python CI Pipeline

# Run on pushes to main and on any pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10" # Use one version for linting

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all dependencies from your requirements file
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Linters (as per your requirements.txt)
      run: |
        pylint $(git ls-files '*.py')
        black --check .
        mypy .

  test:
    name: Run Unit Tests
    needs: lint-and-format  # Don't run tests if linting fails
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        # Test on all OS and Python versions from your docs
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pytest
      run: |
        # Run tests and generate a coverage report
        pytest --cov=. --cov-report=xml