name: Pylint

# Trigger the action on push events
on: [push]

jobs:
  build:
    # The job runs on the latest Ubuntu image
    runs-on: ubuntu-latest
    
    strategy:
      # Testing against multiple Python versions
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
    # Step to check out the code from the repository
    - uses: actions/checkout@v4

    # Step to set up the Python environment using the specified Python versions
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step to install dependencies, including Pylint
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Step to run Pylint on all Python files in the repository
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
